config/routes.rb
Rails.application.routes.draw do
  get '/answer' => 'coaching#answer'

  get '/ask' => 'coaching#ask'

  root 'coaching#ask'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coaching_controller.rb
class CoachingController < ApplicationController


 def answer
    @question = params[:question]
    @answer = ""
    end_message = "I am going to work right now!"
    if @question != end_message && @question != end_message.upcase
      if (@question == @question.upcase)
        motivation_message = "I can feel your motivation!"
        @answer = motivation_message + " "
      end
        if @question == "I am going to work right now!"
          @answer << ""
        else
          if (@question[-1, 1] == "?")
            @answer << "Silly question, get dressed and go to work!"
          else
            @answer << "I don't care, get dressed and go to work!"
          end
        end
    end
  end

  def ask
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaching_helper.rb
module CoachingHelper
end

app/views/coaching/answer.html.erb
<h1><%=@question %></h1>
<h3>-You</h3>
<h1><%=@answer %></h1>
<h3>-Your Coach</h3>
<%= link_to "Ask a new question, if you dare", ask_path %>

app/views/coaching/ask.html.erb
<h1>Stupid coach</h1>

<form action="/answer">
  <label for="question">Speak to your coach</label>
  <input type="text" id="question" name="question" placeholder="what time is it?">
  <input type="submit" value="Go on!">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StupidCoach</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>